CREATE DATABASE Hospital;
USE Hospital;

--patient management
CREATE TABLE PatientPersonalInfo(
	PatientID INT NOT NULL UNIQUE IDENTITY(1,1),
	FullName VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Gender VARCHAR(1) NOT NULL,
	PhoneNumber VARCHAR(10) NOT NULL,
	EMail VARCHAR(20) NOT NULL,
	EmergencyContactName VARCHAR(25),
	EmergencyContactNumber VARCHAR(101),
	IDNumber VARCHAR(13) NOT NULL UNIQUE,

	PRIMARY KEY (PatientID)
);
DROP TABLE PatientPersonalInfo;

CREATE TABLE PatientMedInfo(
	--MedicalHistory
	--Allergies
	--Current_Medications
	PrimaryCarePhysician VARCHAR(50) NOT NULL
	--InsuranceInformation
);

CREATE TABLE PatientVisitInfo(
	PatientID INT NOT NULL,
	AdmissionDate DATE NOT NULL,
	DischargeDate DATE NOT NULL,
	VisitReason VARCHAR(25) NOT NULL,
	AssignedDoctor INT NOT NULL,
	BedNumber VARCHAR(3) NOT NULL,

	FOREIGN KEY(PatientID) REFERENCES PatientPersonlaInfo
);

--doctor management
CREATE TABLE StaffPersonalInfo();
CREATE TABLE StaffProffessionalInfo();


2. Doctor/Nurse Management
Personal Information
Full Name
Date of Birth
Gender
Contact Information (phone number, email, address)

Professional Information
Specialization
Qualifications
Years of Experience
License Number
Department
Shift Timings
Availability Status

3. Appointment Management
Appointment Details
Appointment ID
Patient Name
Doctor Name
Appointment Date and Time
Reason for Appointment
Status (Scheduled, Completed, Cancelled)
Notes

4. Billing and Financial Management
Billing Information
Bill Number
Patient Name
Services Provided
Medications Prescribed
Total Amount
Payment Status (Paid, Unpaid, Partially Paid)
Payment Method (Cash, Credit Card, Insurance)

5. Inventory Management
Inventory Details
Item Name
Item Code
Quantity in Stock
Reorder Level
Supplier Information
Purchase Date
Expiry Date

6. Laboratory and Diagnostic Management
Test Information
Test Name
Test Code
Patient Name
Doctor Name
Test Date
Results
Status (Pending, Completed)
Notes

7. Staff Management
Personal Information
Full Name
Date of Birth
Gender
Contact Information
Employment Information
Role (Admin, Receptionist, Technician, etc.)
Department
Date of Joining
Work Schedule
Salary Details
Emergency Contact Information

8. Room and Bed Management
Room Information
Room Number
Type (General, ICU, Private, etc.)
Bed Count
Occupancy Status
Assigned Staff
Cleaning Schedule

9. Pharmacy Management
Medication Information
Medication Name
Medication Code
Quantity Available
Dosage
Expiry Date
Supplier Information

10. Reporting and Analytics
Report Details
Report ID
Report Type (Financial, Inventory, Patient Statistics, etc.)
Generation Date
Generated By
Summary